# Generated by Django 4.0 on 2021-12-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='title', max_length=100)),
                ('author', models.CharField(blank=True, default='author', max_length=100)),
                ('language', models.CharField(blank=True, default='Language', max_length=20)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
